### ISSUE TITLE
Undeclared dependency on `termcolor` Python package

### ISSUE THREAD

**Issue by follower** [scriptotek/pyrfidgeek#1]
Thanks for your work on this package.

I've had success (only tested reading) using this package with the DLP Design DLP-RFID2D USB stick.

I did run into one issue:

 * The library has a dependency on `termcolor` but it's not declared as a dependency/requirement anywhere: https://github.com/scriptotek/pyrfidgeek/blob/d74440f8c4faf8e508859024ddddd4d96d6fd49b/rfidgeek/rfidgeek.py#L9

Given that it's only used for (optional) logging it seems reasonable to not change to require `termcolor` but rather provide a "pass through" implementation of the function `colored()` used.

In the interim I just installed the required library via:

    pip install termcolor

Thanks again for your efforts!

**Comment by danmichaelo** [comment]
Fixed!

Interesting RFID stick btw. – I might check that one out :)
